CREATE TABLE `Unit` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `Unit_name_key` (`name`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `Unit` (`name`) VALUES
    ('BES'),
    ('CCA'),
    ('CCM'),
    ('CCW'),
    ('CMS'),
    ('CSD'),
    ('DPO'),
    ('FIN'),
    ('GRA'),
    ('HRD'),
    ('HSU'),
    ('IST'),
    ('MIC'),
    ('OIA'),
    ('OLA'),
    ('OSA'),
    ('OUP'),
    ('QMO'),
    ('RIS'),
    ('SAS'),
    ('SEA'),
    ('SMC'),
    ('SMI'),
    ('SFW'),
    ('SNA'),
    ('SOL'),
    ('SOM'),
    ('SRH'),
    ('STL'),
    ('TLC'),
    ('UIO'),
    ('UOP'),
    ('UNL'),
    ('URO'),
    ('VAA'),
    ('VVFI'),
    ('VMI'),
    ('UFESLU'),
    ('UG ACAD'),
    ('POO');